//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace project.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class detail
    {
        public int detailId { get; set; }
        public int Quantity { get; set; }
        public int headerId { get; set; }
        public int ramenId { get; set; }
    
        public virtual header header { get; set; }
        public virtual ramen ramen { get; set; }
    }
}
